/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Dao;
import Controller.UrlKN;
import Controller.XLDL;
import csdl.TblKhachsan;
import csdl.TblTinh;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Administrator
 */
public class KhachSan extends javax.swing.JFrame {
    DefaultTableModel tablemodel;
    XLDL ksdl;
    UrlKN url;
    Dao dao;
    TblTinh t;
    /**
     * Creates new form KhachSan
     */
    public KhachSan() {
        initComponents();
        ksdl=new XLDL();
        loadKS();
        url=new UrlKN();
        dao= new Dao(url.knURL());
        loadmaTinh();
    }
    void loadKS(){
        ArrayList<TblKhachsan>list;
        try{
            list = ksdl.getListKS();
            tablemodel = (DefaultTableModel) tblKS.getModel();
            for(TblKhachsan ks : list){
                tablemodel.addRow(new Object[]{ks.getMaks(), ks.getTenks(), ks.getDiachi(), ks.getTentinh(), ks.getDanhgia(), ks.getSdtlienhe()});
            }
        }catch(SQLException ex){
            
        }
        
    }
    void loadmaTinh(){
        try{
            ArrayList<TblTinh> T= ksdl.getListT();
            for(TblTinh t:T){
                cbotinh.addItem(t);
            }
        }catch(Exception ex){
            
        }
    }
     void hienThi(int i){
        TableModel model= tblKS.getModel();
        txtMaKS.setText(model.getValueAt(i,0).toString());
        txtTenKS.setText(model.getValueAt(i,1).toString());
        txtDC.setText(model.getValueAt(i,2).toString());
        String cbosubT=model.getValueAt(i, 3).toString();
        for(int j=0;j<cbotinh.getItemCount();j++){
            if(cbotinh.getItemAt(j).toString().equalsIgnoreCase(cbosubT)){
                cbotinh.setSelectedIndex(j);
            }
        }
        txtdanhgia.setText(model.getValueAt(i,4).toString());
        txtsdt.setText(model.getValueAt(i,5).toString());
    }
    private boolean KiemTraDL() throws HeadlessException{
        StringBuilder sb= new StringBuilder();
        if(txtTenKS.getText().equals("")){
            sb.append("VUI LÒNG NHẬP TÊN KHÁCH SẠN!\n");
            txtTenKS.setBackground(Color.yellow);
            txtTenKS.requestFocus();
        }
        else{
            txtTenKS.setBackground(Color.white);
            
        }
        if(txtDC.getText().equals("")){
            sb.append("VUI LÒNG NHẬP ĐỊA CHỈ!\n");
            txtDC.setBackground(Color.yellow);
            txtDC.requestFocus();
        }
        else{
            txtDC.setBackground(Color.white);
            
        }
        if(cbotinh.getSelectedItem().equals("")){
            sb.append("VUI LÒNG CHỌN TỈNH!\n");
            cbotinh.setBackground(Color.yellow);
            cbotinh.requestFocus();
        }
        else{
            cbotinh.setBackground(Color.white);
            
        }
         if(txtdanhgia.getText().equals("")){
            sb.append("VUI LÒNG NHẬP PHẦN ĐÁNH GIÁ!\n");
            txtdanhgia.setBackground(Color.yellow);
            txtdanhgia.requestFocus();
        }
        else{
            txtdanhgia.setBackground(Color.white);
            
        }
          if(txtsdt.getText().equals("")){
            sb.append("VUI LÒNG NHẬP SỐ ĐIỆN THOẠI LIÊN HỆ!\n");
            txtsdt.setBackground(Color.yellow);
            txtsdt.requestFocus();
        }
        else{
            txtsdt.setBackground(Color.white);
            
        }
        if(sb.length()>0){
            JOptionPane.showConfirmDialog(this, sb.toString(),"Thông báo",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else{
            return true;
        }
        
    }
    boolean them, sua;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKS = new javax.swing.JTable();
        btnSua = new javax.swing.JLabel();
        btnPhong = new javax.swing.JLabel();
        btnThem = new javax.swing.JLabel();
        btntimkiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnHuy = new javax.swing.JLabel();
        lblMaKS = new javax.swing.JLabel();
        txtMaKS = new javax.swing.JTextField();
        lblTenKS = new javax.swing.JLabel();
        txtTenKS = new javax.swing.JTextField();
        lblDC = new javax.swing.JLabel();
        txtDC = new javax.swing.JTextField();
        lblmatinh = new javax.swing.JLabel();
        cbotinh = new javax.swing.JComboBox<>();
        lblTdg = new javax.swing.JLabel();
        txtdanhgia = new javax.swing.JTextField();
        lblsdt = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        btnXoa = new javax.swing.JLabel();
        btnLuu = new javax.swing.JLabel();
        btnThoat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KHÁCH SẠN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 160, 10));

        tblKS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách sạn", "Tên khách sạn", "Địa chỉ", "Mã tỉnh", "Đánh giá", "SĐT liên hệ"
            }
        ));
        tblKS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKS);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 890, 440));

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_edit_white_24dp.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 580, 110, 40));

        btnPhong.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_night_shelter_white_24dp.png"))); // NOI18N
        btnPhong.setText("Phòng");
        btnPhong.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPhongMouseClicked(evt);
            }
        });
        jPanel1.add(btnPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 580, 110, 40));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_add_white_24dp.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 580, 110, 40));

        btntimkiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btntimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_search_white_24dp.png"))); // NOI18N
        btntimkiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btntimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntimkiemMouseClicked(evt);
            }
        });
        jPanel1.add(btntimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 60, 50, 40));

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKiem.setForeground(new java.awt.Color(102, 102, 102));
        txtTimKiem.setText("Tìm kiếm");
        txtTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTimKiem.setOpaque(false);
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
        });
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        jPanel1.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 60, 280, 40));

        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/baseline_clear_white_24dp.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyMouseClicked(evt);
            }
        });
        jPanel1.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 640, 110, 40));

        lblMaKS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMaKS.setForeground(new java.awt.Color(255, 255, 255));
        lblMaKS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMaKS.setText("MÃ KHÁCH SẠN:");
        jPanel1.add(lblMaKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 40));
        jPanel1.add(txtMaKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 350, 50));

        lblTenKS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTenKS.setForeground(new java.awt.Color(255, 255, 255));
        lblTenKS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTenKS.setText("TÊN KHÁCH SẠN:");
        jPanel1.add(lblTenKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 210, 40));
        jPanel1.add(txtTenKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 350, 50));

        lblDC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDC.setForeground(new java.awt.Color(255, 255, 255));
        lblDC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDC.setText("ĐỊA CHỈ:");
        jPanel1.add(lblDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 210, 40));
        jPanel1.add(txtDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 350, 50));

        lblmatinh.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblmatinh.setForeground(new java.awt.Color(255, 255, 255));
        lblmatinh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblmatinh.setText("TỈNH:");
        jPanel1.add(lblmatinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 210, 40));

        jPanel1.add(cbotinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 350, 50));

        lblTdg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTdg.setForeground(new java.awt.Color(255, 255, 255));
        lblTdg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTdg.setText("ĐÁNH GIÁ:");
        jPanel1.add(lblTdg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 210, 40));
        jPanel1.add(txtdanhgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 350, 50));

        lblsdt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblsdt.setForeground(new java.awt.Color(255, 255, 255));
        lblsdt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblsdt.setText("SĐT:");
        jPanel1.add(lblsdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 585, 210, 40));
        jPanel1.add(txtsdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 350, 50));

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_delete_white_24dp.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 640, 110, 40));

        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_save_white_24dp.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });
        jPanel1.add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 580, 110, 40));

        btnThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/baseline_clear_white_24dp.png"))); // NOI18N
        btnThoat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        txtTimKiem.setText("");
    }//GEN-LAST:event_txtTimKiemFocusGained

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseClicked
        // TODO add your handling code here:
        txtMaKS.setText("");
        txtTenKS.setText("");
        txtDC.setText("");
        txtdanhgia.setText("");
        txtsdt.setText("");
        txtTimKiem.setText("");
        btnThem.setEnabled(true);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
        btnPhong.setEnabled(true);
        txtTenKS.requestFocus();
        tblKS.removeAll();
        tablemodel.setRowCount(0);
        loadKS();
    }//GEN-LAST:event_btnHuyMouseClicked
    public static  String tenKS;
    private void btnPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhongMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, tenKS);
        PhongKS pKS= new PhongKS(MaKS);
        pKS.setVisible(true);
    }//GEN-LAST:event_btnPhongMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        them=true;
        sua=false;
        btnThem.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }//GEN-LAST:event_btnThemMouseClicked
    String MaKS;
    private void tblKSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKSMouseClicked
        // TODO add your handling code here:
        int i= tblKS.getSelectedRow();
        hienThi(i);
        TableModel model= tblKS.getModel();
        MaKS=model.getValueAt(i,0).toString();
        tenKS=model.getValueAt(i,1).toString();
        
    }//GEN-LAST:event_tblKSMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        them=false;
        sua=true;
        btnThem.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        int chon= JOptionPane.showConfirmDialog(this,"BẠN CÓ MUỐN XÓA?","Thông báo",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(chon== JOptionPane.YES_OPTION){
                try {
                    Integer Maks= Integer.parseInt(txtMaKS.getText());
                    Connection conn= dao.getConnect();
                    String caulenh="DELETE FROM tbl_khachsan WHERE maks="+Maks;
                    boolean a= dao.Lenh(caulenh, conn);
                    if(a){
                        tblKS.removeAll();
                        tablemodel.setRowCount(0);
                        loadKS();
                        JOptionPane.showMessageDialog(this, "XÓA THÀNH CÔNG!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{ 
                        JOptionPane.showMessageDialog(this, "XÓA KHÔNG THÀNH CÔNG!","Thông báo",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                   
                }
            }
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:
        if(them){
            if(KiemTraDL()){
                try {
                    String tenkhachsan= txtTenKS.getText();
                    String diachi= txtDC.getText();
                    TblTinh t= (TblTinh) cbotinh.getSelectedItem();
                    String matinh=String.valueOf(t.getMatinh());
                    String danhgia= txtdanhgia.getText();
                    String sdt= txtsdt.getText();
                    Connection conn= dao.getConnect();

                    String caulenh="INSERT INTO tbl_khachsan VALUES (null,'"+tenkhachsan+"','"+diachi+"','"+matinh+"','"+danhgia+"',"+sdt+")";
                    boolean a= dao.Lenh(caulenh, conn);
                    if(a){
                        tblKS.removeAll();
                        tablemodel.setRowCount(0);
                        loadKS();
                        JOptionPane.showMessageDialog(this, "THÊM THÀNH CÔNG!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "THÊM KHÔNG THÀNH CÔNG!","Thông báo",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {

                }
            } else{
                JOptionPane.showMessageDialog(this, "NHẬP SAI VUI LÒNG NHẬP LẠI!","Thông báo",JOptionPane.ERROR_MESSAGE);
            }
        }

        if(sua){
            if(KiemTraDL()){

                try{
                    Integer Maks=Integer.parseInt(txtMaKS.getText());
                    String tenkhachsan= txtTenKS.getText();
                    String diachi= txtDC.getText();
                    TblTinh t= (TblTinh) cbotinh.getSelectedItem();
                    String matinh=String.valueOf(t.getMatinh());
                    String danhgia= txtdanhgia.getText();
                    String sdt= txtsdt.getText();
                    Connection conn= dao.getConnect();
                    String caulenh="UPDATE tbl_khachsan SET tenks='"+tenkhachsan+"',diachi='"+diachi+"',matinh='"+matinh+"',danhgia='"+danhgia+"',sdtlienhe='"+sdt+"'where maks="+Maks;
                    boolean a= dao.Lenh(caulenh, conn);
                    if(a){
                        tblKS.removeAll();
                        tablemodel.setRowCount(0);
                        loadKS();
                        JOptionPane.showMessageDialog(this, "SỬA THÀNH CÔNG!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "SỬA KHÔNG THÀNH CÔNG!","Thông báo",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {

                }
            }
            else{
                JOptionPane.showMessageDialog(this, "NHẬP SAI VUI LÒNG NHẬP LẠI!","Thông báo",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnLuuMouseClicked

    private void btntimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntimkiemMouseClicked
        // TODO add your handling code here:
        tblKS.removeAll();
        tablemodel.setRowCount(0);
        
        String timkiem=txtTimKiem.getText();
        ArrayList<TblKhachsan>list;
        try{
        list = ksdl.getListKS(timkiem);
        tablemodel = (DefaultTableModel) tblKS.getModel();
        for(TblKhachsan ks : list){
            tablemodel.addRow(new Object[]{ks.getMaks(), ks.getTenks(), ks.getDiachi(), ks.getTentinh(), ks.getDanhgia(), ks.getSdtlienhe()});
        }
        }catch(SQLException ex){
            
        }
    }//GEN-LAST:event_btntimkiemMouseClicked

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachSan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachSan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHuy;
    private javax.swing.JLabel btnLuu;
    private javax.swing.JLabel btnPhong;
    private javax.swing.JLabel btnSua;
    private javax.swing.JLabel btnThem;
    private javax.swing.JLabel btnThoat;
    private javax.swing.JLabel btnXoa;
    private javax.swing.JLabel btntimkiem;
    private javax.swing.JComboBox<TblTinh> cbotinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDC;
    private javax.swing.JLabel lblMaKS;
    private javax.swing.JLabel lblTdg;
    private javax.swing.JLabel lblTenKS;
    private javax.swing.JLabel lblmatinh;
    private javax.swing.JLabel lblsdt;
    private javax.swing.JTable tblKS;
    private javax.swing.JTextField txtDC;
    private javax.swing.JTextField txtMaKS;
    private javax.swing.JTextField txtTenKS;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtdanhgia;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
