/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Dao;
import Controller.UrlKN;
import Controller.XLDL;
import csdl.TblPhuongtien;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Administrator
 */
public class PhuongTien extends javax.swing.JFrame {
    DefaultTableModel tablemodel;
    XLDL ptdl;
    UrlKN url;
    Dao dao;

    /**
     * Creates new form PhuongTien
     */
    public PhuongTien() {
        initComponents();
        ptdl=new XLDL();
        loadPT();
        url=new UrlKN();
        dao= new Dao(url.knURL());
        
    }
    void loadPT(){
        ArrayList<TblPhuongtien>list;
        try{
            list = ptdl.getListPT();
            tablemodel = (DefaultTableModel) tblPt.getModel();
            for(TblPhuongtien pt : list){
                tablemodel.addRow(new Object[]{pt.getMaphuongtien(), pt.getTenphuongtien(), pt.getLoai(), pt.getTentaixe(), pt.getSdtlienlac(), pt.getTrangthai(), pt.getGia()});
            }
        }catch(SQLException ex){
            
        }
        
    }
    void hienThi(int i){
        TableModel model= tblPt.getModel();
        txtMAPT.setText(model.getValueAt(i,0).toString());
        txtTenpt.setText(model.getValueAt(i,1).toString());
        txtloai.setText(model.getValueAt(i,2).toString());
        txttaixe.setText(model.getValueAt(i,3).toString());
        txtSDT.setText(model.getValueAt(i,4).toString());
        cboTrangthai.setSelectedItem(model.getValueAt(i,5).toString());
        frmGia.setText(model.getValueAt(i,6).toString());
    }
    private boolean KiemTraDL() throws HeadlessException{
        StringBuilder sb= new StringBuilder();
        if(txtTenpt.getText().equals("")){
            sb.append("VUI LÒNG NHẬP TÊN PHƯƠNG TIỆN!\n");
            txtTenpt.setBackground(Color.yellow);
            txtTenpt.requestFocus();
        }
        else{
            txtTenpt.setBackground(Color.white);
            
        }
        if(txtloai.getText().equals("")){
            sb.append("VUI LÒNG NHẬP LOẠI!\n");
            txtloai.setBackground(Color.yellow);
            txtloai.requestFocus();
        }
        else{
            txtloai.setBackground(Color.white);
            
        }
        if(txttaixe.getText().equals("")){
            sb.append("VUI LÒNG NHẬP TÊN TÀI XẾ!\n");
            txttaixe.setBackground(Color.yellow);
            txttaixe.requestFocus();
        }
        else{
            txttaixe.setBackground(Color.white);
            
        }
        if(txtSDT.getText().equals("")){
            sb.append("VUI LÒNG NHẬP SĐT!\n");
            txtSDT.setBackground(Color.yellow);
            txtSDT.requestFocus();
        }
        else{
            txtSDT.setBackground(Color.white);
            
        }
        if(cboTrangthai.getSelectedItem().equals("")){
            sb.append("VUI LÒNG CHỌN TRẠNG THÁI!\n");
            cboTrangthai.setBackground(Color.yellow);
            cboTrangthai.requestFocus();
        }
        else{
            cboTrangthai.setBackground(Color.white);
            
        }
         if(frmGia.getText().equals("")){
            sb.append("VUI LÒNG NHẬP GIÁ!\n");
            frmGia.setBackground(Color.yellow);
            frmGia.requestFocus();
        }
        else{
            frmGia.setBackground(Color.white);
            
        }
          
        if(sb.length()>0){
            JOptionPane.showConfirmDialog(this, sb.toString(),"Thông báo",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else{
            return true;
        }
        
    }
    boolean them, sua;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPt = new javax.swing.JTable();
        btntimkiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnThem = new javax.swing.JLabel();
        btnXoa = new javax.swing.JLabel();
        lblMapt = new javax.swing.JLabel();
        txtMAPT = new javax.swing.JTextField();
        lblTenpt = new javax.swing.JLabel();
        txtTenpt = new javax.swing.JTextField();
        lblTenKS1 = new javax.swing.JLabel();
        txtloai = new javax.swing.JTextField();
        lbltaixe = new javax.swing.JLabel();
        txttaixe = new javax.swing.JTextField();
        lbltrangthai = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        cboTrangthai = new javax.swing.JComboBox<>();
        frmGia = new javax.swing.JFormattedTextField();
        btnSua = new javax.swing.JLabel();
        btnLuu = new javax.swing.JLabel();
        btnHuy = new javax.swing.JLabel();
        btnThoat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 190, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PHƯƠNG TIỆN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, -1));

        tblPt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phương tiện", "Tên phương tiện", "Loại", "Tên tài xế", "SĐT liên lạc", "Trạng thái", "Giá"
            }
        ));
        tblPt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1370, 300));

        btntimkiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btntimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_search_white_24dp.png"))); // NOI18N
        btntimkiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btntimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntimkiemMouseClicked(evt);
            }
        });
        jPanel1.add(btntimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 50, 40, 40));

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKiem.setForeground(new java.awt.Color(102, 102, 102));
        txtTimKiem.setText("Tìm kiếm");
        txtTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTimKiem.setOpaque(false);
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
        });
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        jPanel1.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, 280, 40));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_add_white_24dp.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 640, 120, 50));

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_delete_white_24dp.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 640, 120, 50));

        lblMapt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMapt.setForeground(new java.awt.Color(255, 255, 255));
        lblMapt.setText("MÃ PHƯƠNG TIỆN:");
        jPanel1.add(lblMapt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 240, 40));
        jPanel1.add(txtMAPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 350, 50));

        lblTenpt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTenpt.setForeground(new java.awt.Color(255, 255, 255));
        lblTenpt.setText("TÊN PHƯƠNG TIỆN:");
        jPanel1.add(lblTenpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, 40));
        jPanel1.add(txtTenpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 350, 50));

        lblTenKS1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTenKS1.setForeground(new java.awt.Color(255, 255, 255));
        lblTenKS1.setText("LOẠI:");
        jPanel1.add(lblTenKS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 150, 40));
        jPanel1.add(txtloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 350, 50));

        lbltaixe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbltaixe.setForeground(new java.awt.Color(255, 255, 255));
        lbltaixe.setText("TÀI XẾ:");
        jPanel1.add(lbltaixe, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 150, 40));
        jPanel1.add(txttaixe, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 360, 50));

        lbltrangthai.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbltrangthai.setForeground(new java.awt.Color(255, 255, 255));
        lbltrangthai.setText("TRẠNG THÁI:");
        jPanel1.add(lbltrangthai, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, 190, 40));

        lblGia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblGia.setForeground(new java.awt.Color(255, 255, 255));
        lblGia.setText("GIÁ:");
        jPanel1.add(lblGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 510, 150, 40));

        lblSDT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(255, 255, 255));
        lblSDT.setText("SĐT TÀI XẾ:");
        jPanel1.add(lblSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 180, 40));
        jPanel1.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 360, 50));

        cboTrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống", "Đã cho thuê" }));
        jPanel1.add(cboTrangthai, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 450, 360, 50));
        jPanel1.add(frmGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 560, 360, 50));

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_edit_white_24dp.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 640, 120, 50));

        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/outline_save_white_24dp.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });
        jPanel1.add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 640, 120, 50));

        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/baseline_clear_white_24dp.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyMouseClicked(evt);
            }
        });
        jPanel1.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 640, 120, 50));

        btnThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/baseline_clear_white_24dp.png"))); // NOI18N
        btnThoat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        txtTimKiem.setText("");
    }//GEN-LAST:event_txtTimKiemFocusGained

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        them=false;
        sua=true;
        btnThem.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:
        if(them){
            if(KiemTraDL()){
                try {
                    String tenpt= txtTenpt.getText().toString();
                    String loai= txtloai.getText().toString();
                    String taixe= txttaixe.getText().toString();
                    String sdt= txtSDT.getText().toString();
                    String trangthai= cboTrangthai.getSelectedItem().toString();
                    String gia= frmGia.getText().toString();
                    Connection conn= dao.getConnect();

                    String caulenh="INSERT INTO tbl_phuongtien VALUES (null,'"+tenpt+"','"+loai+"','"+taixe+"','"+sdt+"','"+trangthai+"',"+gia+")";
                    boolean a= dao.Lenh(caulenh, conn);
                    if(a){
                        tblPt.removeAll();
                        tablemodel.setRowCount(0);
                        loadPT();
                        JOptionPane.showMessageDialog(this, "THÊM THÀNH CÔNG!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "THÊM KHÔNG THÀNH CÔNG!","Thông báo",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {

                }
            } else{
                JOptionPane.showMessageDialog(this, "NHẬP SAI VUI LÒNG NHẬP LẠI!","Thông báo",JOptionPane.ERROR_MESSAGE);
            }
        }

        if(sua){
            if(KiemTraDL()){

                try{
                    Integer Mapt=Integer.parseInt(txtMAPT.getText());
                    String tenpt= txtTenpt.getText().toString();
                    String loai= txtloai.getText().toString();
                    String taixe= txttaixe.getText().toString();
                    String sdt= txtSDT.getText().toString();
                    String trangthai= cboTrangthai.getSelectedItem().toString();
                    String gia= frmGia.getText().toString();
                    Connection conn= dao.getConnect();
                    String caulenh="UPDATE tbl_phuongtien SET tenphuongtien='"+tenpt+"',loai='"+loai+"',tentaixe='"+taixe+"',sdtlienlac='"+sdt+"',trangthai='"+trangthai+"'where maphuongtien="+Mapt;
                    boolean a= dao.Lenh(caulenh, conn);
                    if(a){
                        tblPt.removeAll();
                        tablemodel.setRowCount(0);
                        loadPT();
                        JOptionPane.showMessageDialog(this, "SỬA THÀNH CÔNG!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "SỬA KHÔNG THÀNH CÔNG!","Thông báo",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {

                }
            }
            else{
                JOptionPane.showMessageDialog(this, "NHẬP SAI VUI LÒNG NHẬP LẠI!","Thông báo",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnLuuMouseClicked

    private void btnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseClicked
        // TODO add your handling code here:
        txtMAPT.setText("");
        txtTenpt.setText("");
        txtloai.setText("");
        txttaixe.setText("");
        txtSDT.setText("");
        frmGia.setText("");
        txtTimKiem.setText("");
        btnThem.setEnabled(true);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
        txtTenpt.requestFocus();
        tblPt.removeAll();
        tablemodel.setRowCount(0);
        loadPT();
    }//GEN-LAST:event_btnHuyMouseClicked

    private void btntimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntimkiemMouseClicked
        // TODO add your handling code here:
        tblPt.removeAll();
        tablemodel.setRowCount(0);
        
        String timkiem=txtTimKiem.getText();
        ArrayList<TblPhuongtien>list;
        try{
        list = ptdl.getListPT(timkiem);
        tablemodel = (DefaultTableModel) tblPt.getModel();
        for(TblPhuongtien pt : list){
            tablemodel.addRow(new Object[]{pt.getMaphuongtien(), pt.getTenphuongtien(), pt.getLoai(), pt.getTentaixe(), pt.getSdtlienlac(), pt.getTrangthai(), pt.getGia()});
        }
        }catch(SQLException ex){
            
        }
    }//GEN-LAST:event_btntimkiemMouseClicked

    private void tblPtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPtMouseClicked
        // TODO add your handling code here:
        int i= tblPt.getSelectedRow();
        hienThi(i);
    }//GEN-LAST:event_tblPtMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        them=true;
        sua=false;
        btnThem.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        int chon= JOptionPane.showConfirmDialog(this,"BẠN CÓ MUỐN XÓA?","Thông báo",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(chon== JOptionPane.YES_OPTION){
                try {
                    Integer Mapt= Integer.parseInt(txtMAPT.getText());
                    Connection conn= dao.getConnect();
                    String caulenh="DELETE FROM tbl_phuongtien WHERE maphuongtien="+Mapt;
                    boolean a= dao.Lenh(caulenh, conn);
                    if(a){
                        tblPt.removeAll();
                        tablemodel.setRowCount(0);
                        loadPT();
                        JOptionPane.showMessageDialog(this, "XÓA THÀNH CÔNG!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{ 
                        JOptionPane.showMessageDialog(this, "XÓA KHÔNG THÀNH CÔNG!","Thông báo",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                   
                }
            }
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhuongTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhuongTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhuongTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhuongTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhuongTien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHuy;
    private javax.swing.JLabel btnLuu;
    private javax.swing.JLabel btnSua;
    private javax.swing.JLabel btnThem;
    private javax.swing.JLabel btnThoat;
    private javax.swing.JLabel btnXoa;
    private javax.swing.JLabel btntimkiem;
    private javax.swing.JComboBox<String> cboTrangthai;
    private javax.swing.JFormattedTextField frmGia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblMapt;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTenKS1;
    private javax.swing.JLabel lblTenpt;
    private javax.swing.JLabel lbltaixe;
    private javax.swing.JLabel lbltrangthai;
    private javax.swing.JTable tblPt;
    private javax.swing.JTextField txtMAPT;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenpt;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtloai;
    private javax.swing.JTextField txttaixe;
    // End of variables declaration//GEN-END:variables
}
