/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Dao;
import Controller.KNCSDL;
import Controller.UrlKN;
import Controller.XLDL;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import csdl.TblChitietdiemdanh;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class QuetMa extends javax.swing.JFrame implements Runnable, ThreadFactory{
    DefaultTableModel tablemodel;
    XLDL qmdl;
    UrlKN url;
    Dao dao;
    KNCSDL kn;
    
    private WebcamPanel panel = null;
    private Webcam webcam = null;
    
    private static final long serialVersionUID = 6441489157408381878L;
    private Executor executor = Executors.newSingleThreadExecutor( this);
    private void initWebcam() {
        Dimension size = WebcamResolution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0); //0 is default webcam
        webcam.setViewSize(size);

        panel = new WebcamPanel(webcam);
        panel.setPreferredSize(size);
        panel.setFPSDisplayed(true);

        pnQuet.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 330));

        executor.execute(this);
    }

    @Override
    public void run() {
        do {
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            Result result = null;
            BufferedImage image = null;

            if (webcam.isOpen()) {
                if ((image = webcam.getImage()) == null) {
                    continue;
                }
            }

            LuminanceSource source = new BufferedImageLuminanceSource(image);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

            try {
                result = new MultiFormatReader().decode(bitmap);
            } catch (NotFoundException e) {
                //No result...
            }

            if (result != null) {
                txtMaNV.setText(result.getText());
                
               
            }
        } while (true);
    }

    @Override
    public Thread newThread(Runnable r) {
        Thread t = new Thread(r, "My Thread");
        t.setDaemon(true);
        return t;
    }
    /**
     * Creates new form QuetMa
     */
    public QuetMa() {
        initComponents();
        initWebcam();
        qmdl=new XLDL();
        url=new UrlKN();
        dao= new Dao(url.knURL());
        kn=new KNCSDL();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnQuet = new javax.swing.JPanel();
        btnChamCongRa = new javax.swing.JLabel();
        btnChamCongVao = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        lblHoTen = new javax.swing.JLabel();
        txtngay = new javax.swing.JTextField();
        lblTrangThai = new javax.swing.JLabel();
        txtTrangThaai = new javax.swing.JTextField();
        lblNgay = new javax.swing.JLabel();
        lblGioVao = new javax.swing.JLabel();
        txtGioVao = new javax.swing.JTextField();
        lblGioRa = new javax.swing.JLabel();
        txtGioRa = new javax.swing.JTextField();
        btnThoat = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnQuet.setBackground(new java.awt.Color(255, 255, 255));
        pnQuet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnQuet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(pnQuet, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 670, 330));

        btnChamCongRa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnChamCongRa.setForeground(new java.awt.Color(255, 255, 255));
        btnChamCongRa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnChamCongRa.setText("Chấm công ra");
        btnChamCongRa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnChamCongRa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChamCongRaMouseClicked(evt);
            }
        });
        jPanel1.add(btnChamCongRa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 290, 220, 60));

        btnChamCongVao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnChamCongVao.setForeground(new java.awt.Color(255, 255, 255));
        btnChamCongVao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnChamCongVao.setText("Chấm công vào");
        btnChamCongVao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnChamCongVao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChamCongVaoMouseClicked(evt);
            }
        });
        jPanel1.add(btnChamCongVao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 230, 220, 60));

        lblMaNV.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMaNV.setForeground(new java.awt.Color(255, 255, 255));
        lblMaNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMaNV.setText("MÃ NV:");
        jPanel1.add(lblMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 140, 40));
        jPanel1.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 350, 50));

        lblHoTen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(255, 255, 255));
        lblHoTen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHoTen.setText("HỌ TÊN:");
        jPanel1.add(lblHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, 110, 40));
        jPanel1.add(txtngay, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, 350, 50));

        lblTrangThai.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(255, 255, 255));
        lblTrangThai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTrangThai.setText("TRẠNG THÁI:");
        jPanel1.add(lblTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 170, 40));
        jPanel1.add(txtTrangThaai, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 350, 50));

        lblNgay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNgay.setForeground(new java.awt.Color(255, 255, 255));
        lblNgay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNgay.setText("NGÀY:");
        jPanel1.add(lblNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, 110, 40));

        lblGioVao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblGioVao.setForeground(new java.awt.Color(255, 255, 255));
        lblGioVao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGioVao.setText("GIỜ VÀO:");
        jPanel1.add(lblGioVao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 140, 40));
        jPanel1.add(txtGioVao, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, 350, 50));

        lblGioRa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblGioRa.setForeground(new java.awt.Color(255, 255, 255));
        lblGioRa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGioRa.setText("GIỜ RA:");
        jPanel1.add(lblGioRa, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 600, 110, 40));

        txtGioRa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioRaActionPerformed(evt);
            }
        });
        jPanel1.add(txtGioRa, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, 350, 50));

        btnThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/baseline_clear_white_24dp.png"))); // NOI18N
        btnThoat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 40, 40));
        jPanel1.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 350, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGioRaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGioRaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGioRaActionPerformed

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        if (webcam.isOpen()) {
            webcam.close();
        }
    }//GEN-LAST:event_btnThoatMouseClicked
    Integer getchamcong(String ma) throws SQLException {
        KNCSDL kn = new KNCSDL();
        ArrayList<TblChitietdiemdanh> list = new ArrayList<>();
        Connection conn = kn.getConnect();
        String sql = "SELECT tbl_chitietdiemdanh.* FROM tbl_chitietdiemdanh where ngay = date(Now()) and giovao= time(Now()) and manv=" + ma;
        Statement statement = (Statement) conn.createStatement();
        ResultSet result = statement.executeQuery(sql);
        int a = 0;
        while (result.next()) {

            a++;
        }
        return a;
    }
    private void btnChamCongVaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChamCongVaoMouseClicked
        // TODO add your handling code here:
        try {
            Connection conn = dao.getConnect();
            int getcc = getchamcong(txtMaNV.getText());
            if (getcc == 0) {
                String caulenh = "INSERT INTO tbl_chitietdiemdanh VALUES(null,"+txtMaNV.getText()+",date(now()),time(now()),time(now()),'ghi chú','trạng thái')";
                boolean a = dao.Lenh(caulenh, conn);
                if(a){
                    getten(txtMaNV.getText());
                }
            } else {

            }
            
          
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_btnChamCongVaoMouseClicked

    private void btnChamCongRaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChamCongRaMouseClicked
        // TODO add your handling code here:
        try {
            Connection conn = dao.getConnect();
            

            String cl = "Update tbl_chitietdiemdanh set GioRa=time(now()) where manv=" + txtMaNV.getText() + " and ngay=date(now())";
            boolean a = dao.Lenh(cl, conn);
            if(a){
                    getten(txtMaNV.getText());
                }

            
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_btnChamCongRaMouseClicked
     public void getten(String ma) throws SQLException{
     
  
        Connection conn = kn.getConnect();
        String sql = "SELECT * FROM  tbl_nhanvien WHERE manv="+ma;
        Statement statement = (Statement) conn.createStatement();
        ResultSet result = statement.executeQuery(sql);
        while (result.next()) {
            txtHoTen.setText(result.getString(2));
            
        }
        Date dt = new Date();
                SimpleDateFormat timed = new SimpleDateFormat("hh:mm:ss", Locale.getDefault());
                String time = timed.format(dt.getTime());
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String ngay = dateFormat.format(dt);
        txtGioVao.setText(time);
        txtngay.setText(ngay);
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuetMa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuetMa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuetMa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuetMa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuetMa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnChamCongRa;
    private javax.swing.JLabel btnChamCongVao;
    private javax.swing.JLabel btnThoat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGioRa;
    private javax.swing.JLabel lblGioVao;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnQuet;
    private javax.swing.JTextField txtGioRa;
    private javax.swing.JTextField txtGioVao;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtTrangThaai;
    private javax.swing.JTextField txtngay;
    // End of variables declaration//GEN-END:variables

    
}
